# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
